name: 'Docker'

# on:
#   pull_request:
#     types:
#       - closed
#     branches:    
#       - 'master-omolade-ekpeni'
on:
  push:
    branches:
      -  'master-omolade-ekpeni'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  # IMAGE_TAG: ${{ steps.date.outputs.date }}

jobs:
  build_and_push_to_registry:
    name: Build and push Docker image to GHCR
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
    contents: read
    packages: write
    
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to GHCR
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

            # get the date of the build
      - name: Get Current Date 
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d--%M-%S')"

      - name: Build Docker Image
        run: docker build . --file Dockerfile --tag  ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.date.outputs.date }}

      - name: Push Docker Image to Docker Hub
        run: docker push  ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.date.outputs.date }}
      # nodejs_ci is the repository name