name: 'Docker'
on:
  pull_request:
    types:
      - closed
    branches:    
      - 'master-omolade-ekpeni'

jobs:
  build_and_push_to_registry:
    name: Build and push Docker Image to ECR
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest    
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Log in to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # get the date of the build
      - name: Get Current Date 
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d--%M-%S')"

      - name: Build and Push Docker Image to AWS ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: github_ci

        run: |
          docker build . --file Dockerfile --tag  $ECR_REGISTRY/$ECR_REPOSITORY:${{ steps.date.outputs.date }}
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:${{ steps.date.outputs.date }}

