name: Notify  Slack on push
on:
  push:
    branches:
      -  'master-omolade-ekpeni'  

jobs:
  notify_push:
    name: Notify Slack on pushes
    runs-on: ubuntu-latest
    steps:
      - name: Notify slack success
        if: always()
        uses: wearerequired/slack-messaging-action@v1
        with:
          bot_token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel: githubactions
          payload: >-
            {
                "icon_emoji": ":rocket:",
                "username": "Deployer",
                "attachments": [
                    {
                        "author_name": "${{ github.event.sender.login }}",
                        "author_link": "${{ github.event.sender.html_url }}",
                        "author_icon": "${{ github.event.sender.avatar_url }}",
                        "color": "good",
                        "fallback": "Deployment Finished",
                        "pretext": "Finished deploying  ${{ github.ref_name }} to ${{ github.event.inputs.choice }} for ${{ github.event.repository.name }}.",
                        "fields": [
                            {
                              "title": "Revision",
                              "value": "<https://github.com/${{ github.repository }}/commit/${{ github.sha }}|${{ github.sha }}@${{ github.ref }}>",
                              "short": true
                            }
                          ],
                        "footer": "<https://github.com/${{ github.repository }}|${{ github.repository }}>"
                    }
                ]
            }











      # - uses: abinoda/slack-action@master
      #   env:
      #     SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      #   with:
      #     # custom message to send to slack
      #     args: '{\"channel\":\"${{ secrets.SLACK_PR_CHANNEL_ID }}\",\"blocks\":[{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"*Repository pushed to:* ${{ github.event.repository.name }}\"}},{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"*Pusher:* ${{ github.event.pusher.name }}\n*Commit Message:* ${{ github.event.head_commit.message }}\"}},{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"<${{ github.event.repository.html_url }}|View Repository>\"}}]}' 
      #   # Pick up events if the job is successful.
      #   if: success()







      # works but message cnnot be modified
      # - uses: actions/checkout@v2
      # - run: exit 0
      # - name: Slack Success
        # if: always()
        # uses: kpritam/slack-job-status-action@v1
        # with:
          # job-status: ${{ job.status }}
          # slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          # channel: githubactions
# 
  # failure-notification:
    # runs-on: ubuntu-latest
    # steps:
      # - uses: actions/checkout@v2
      # - run: exit 1
      # - name: Slack Failure
        # if: always()
        # uses: kpritam/slack-job-status-action@v1
        # with:
          # job-status: ${{ job.status}}
          # slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          # channel: githubactions

        






# works too but cannot be modified
      #   - name: Notify slack success
      #   if: always()
      #   id: slack # IMPORTANT: reference this step ID value in future Slack steps
      #   env:
      #     SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      #   uses: voxmedia/github-action-slack-notify-build@v1
      #   with:
      #     channel_id: C03QAA7BNCC
      #     status: STARTING
      #     color: warning

      # # - name: Run tests
      # # ... your test step here
      # - name: Notify slack success
      #   if: success()
      #   env:
      #     SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      #   uses: voxmedia/github-action-slack-notify-build@v1
      #   with:
      #       # Updates existing message from the first step
      #     message_id: ${{ steps.slack.outputs.message_id }}
      #     channel_id: C03QAA7BNCC
      #     status: SUCCESS
      #     color: good
