name: Notify  Slack on push
on:
  push:
    branches:
      -  'master-omolade-ekpeni'  

jobs:
  notify_push:
    name: Notify Slack on pushes
    runs-on: ubuntu-latest
    steps:
      # - uses: abinoda/slack-action@master
      #   env:
      #     SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      #   with:
      #     # custom message to send to slack
      #     args: '{\"channel\":\"${{ secrets.SLACK_PR_CHANNEL_ID }}\",\"blocks\":[{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"*Repository pushed to:* ${{ github.event.repository.name }}\"}},{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"*Pusher:* ${{ github.event.pusher.name }}\n*Commit Message:* ${{ github.event.head_commit.message }}\"}},{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"<${{ github.event.repository.html_url }}|View Repository>\"}}]}' 
      #   # Pick up events if the job is successful.
      #   if: success()
      - uses: actions/checkout@v2
      - run: exit 0
      - name: Slack Success
        if: always()
        uses: kpritam/slack-job-status-action@v1
        with:
          job-status: ${{ job.status }}
          slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel: githubactions

  failure-notification:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: exit 1
      - name: Slack Failure
        if: always()
        uses: kpritam/slack-job-status-action@v1
        with:
          job-status: ${{ job.status  '{\"channel\":\"${{ secrets.CODESPARK_STAGING_SLACK_CHANNEL_ID }}\",\"blocks\":[{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"*${{ job.status }}:* deploy ${{ github.ref_name }} to ${{ github.event.inputs.choice }} for ${{ github.event.repository.name }}\"}}]}'}}
          slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel: githubactions
      