
# Name of workflow to be displyed on Github Console
name: Notify on Slack

# Triggers the workflow on separate events 
on:
  pull_request:
    types:
      - closed
    branches:    
      - 'master-omolade-ekpeni'
  push:
    # Trigger the worflow on push event for the  branch specified
    branches:
      -  'master-omolade-ekpeni'  

jobs:
  notify_merged_pull_request:
    name: Notify Slack on merged pull requests
    runs-on: ubuntu-latest
    if: ${{ github.base_ref == 'master-omolade-ekpeni' && github.event.pull_request.merged == true }}
    steps:
      - uses: abinoda/slack-action@master
        env:
          # required
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        with:
          # custom message to send to slack
          args: '{\"channel\":\"${{ secrets.SLACK_PR_CHANNEL_ID }}\",\"blocks\":[{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"*Merged Pull Request:* ${{ github.event.pull_request.title }}\"}},{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"*Merged by :* ${{ github.event.pull_request.merged_by }}\n*Merged at:* ${{ github.event.pull_request.merged_at }}\"}},{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"<${{ github.event.pull_request.merges_url }}|View Merged Pull Request>\"}}]}' 
        
        # Pick up events even if the job is success.
        if: success()

  notify_push:
    name: Notify Slack on pushes
    runs-on: ubuntu-latest
    if: ${{ github.base_ref == 'master-omolade-ekpeni' && github.event.push == true }}
    steps:
      - uses: abinoda/slack-action@master
        env:
          # required
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        with:
          # custom message to send to slack
          args: '{\"channel\":\"${{ secrets.SLACK_PR_CHANNEL_ID }}\",\"blocks\":[{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"*Repository pushed to:* ${{ github.event.repository.name }}\"}},{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"*Pusher:* ${{ github.event.pusher.name }}\n*Commit Message:* ${{ github.event.head_commit.message }}\"}},{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"<${{ github.event.repository.head_commit.url }}|View Repository>\"}}]}' 
        
        # Pick up events even if the job is success.
        if: success()

  